<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CallPilot.Server.Api\CallPilot.Server.Api.csproj" />
    <ProjectReference Include="..\CallPilot.Server.Application\CallPilot.Server.Application.csproj" />
    <ProjectReference Include="..\CallPilot.Server.Domain\CallPilot.Server.Domain.csproj" />
    <ProjectReference Include="..\CallPilot.Server.Infrastructure\CallPilot.Server.Infrastructure.csproj" />
    <ProjectReference Include="..\CallPilot.Server.Shared\CallPilot.Server.Shared.csproj" />
  </ItemGroup>

</Project>