'use client';

// LocalSummaryView - renders a meeting summary generated by the local LLM.
// Structured sections render only when data exists; generation progress,
// failures and unsaved states are surfaced without faking progress.

import { RefreshCw, Download, LoaderIcon, Sparkles } from 'lucide-react';
import { useRouter } from 'next/navigation';
import type { LocalSummaryState } from '@/hooks/useLocalSummarization';
import type { SummaryProgressEvent } from '@/lib/llm';

interface Props {
  summary: any;
  state?: LocalSummaryState;
  progress?: SummaryProgressEvent | null;
  error?: string | null;
  onRegenerate?: () => void;
  onRetrySave?: () => void;
}

const STAGE_LABELS: Record<string, string> = {
  preparing: 'Preparing transcript',
  summarizing: 'Summarizing discussion',
  synthesizing: 'Extracting key points',
  finalizing: 'Finalizing summary',
  saving: 'Saving summary',
};

function Section({ title, items }: { title: string; items: string[] }) {
  if (!items || items.length === 0) return null;
  return (
    <div className="pt-4 first:pt-0">
      <p className="text-overline mb-1.5 text-[var(--opaline-on-surface-variant)]">{title}</p>
      <ul className="space-y-1">
        {items.map((item, i) => (
          <li key={i} className="flex items-start gap-1.5 text-[13px] leading-[1.5] text-[var(--opaline-on-surface-variant)]">
            <span aria-hidden className="mt-[7px] h-1 w-1 shrink-0 rounded-full bg-[var(--opaline-outline)]" />
            <span className="min-w-0">{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

const STEPS = ['Preparing transcript', 'Summarizing discussion', 'Extracting key points', 'Finalizing summary'];

function ProgressPanel({ progress, saving }: { progress: SummaryProgressEvent; saving: boolean }) {
  const activeStep = progress.stage === 'saving' ? 'Saving summary' : STAGE_LABELS[progress.stage] ?? 'Summarizing';
  return (
    <div className="rounded-xl border border-[var(--opaline-outline-variant)] bg-[var(--opaline-surface-container-lowest)] p-5 shadow-xs">
      <div className="flex items-center gap-2 text-body-md font-medium text-[var(--opaline-on-surface)]">
        <LoaderIcon className="h-4 w-4 animate-spin text-[var(--opaline-primary)]" aria-hidden />
        {saving ? 'Saving summary…' : 'Generating summary locally…'}
      </div>
      <div className="mt-3 space-y-1">
        {STEPS.map((step) => {
          const active =
            !saving &&
            (STAGE_LABELS[progress.stage] === step ||
              (step === 'Preparing transcript' && progress.percent >= 2) ||
              (step === 'Finalizing summary' && progress.stage === 'finalizing'));
          const done =
            !saving &&
            ((step === 'Preparing transcript' && progress.percent > 5) ||
              (step === 'Summarizing discussion' && progress.stage === 'synthesizing') ||
              (step === 'Extracting key points' && progress.stage === 'finalizing') ||
              (step === 'Finalizing summary' && progress.stage === 'saving'));
          return (
            <div key={step} className="flex items-center gap-2 text-[12px] text-[var(--opaline-on-surface-variant)]">
              <span
                className={`flex h-4 w-4 items-center justify-center rounded-full border ${
                  done
                    ? 'border-[var(--opaline-success)] bg-[var(--opaline-success)] text-[var(--opaline-on-success)]'
                    : active
                      ? 'border-[var(--opaline-primary)] text-[var(--opaline-primary)]'
                      : 'border-[var(--opaline-outline)] text-transparent'
                }`}
              >
                {done ? '✓' : ''}
              </span>
              <span className={active ? 'font-medium text-[var(--opaline-on-surface)]' : ''}>{step}</span>
              {active && !done && <LoaderIcon className="h-3 w-3 animate-spin text-[var(--opaline-primary)]" />}
            </div>
          );
        })}
      </div>
    </div>
  );
}

export const LocalSummaryView: React.FC<Props> = ({
  summary,
  state = 'idle',
  progress,
  error,
  onRegenerate,
  onRetrySave,
}) => {
  const router = useRouter();

  if (state === 'summarizing' || state === 'saving') {
    return (
      <ProgressPanel
        progress={progress ?? { stage: state === 'saving' ? 'saving' : 'preparing', percent: 2 }}
        saving={state === 'saving'}
      />
    );
  }

  if (state === 'pending-save') {
    return (
      <div className="rounded-xl border border-[var(--opaline-outline-variant)] bg-[var(--opaline-surface-container-lowest)] p-5 shadow-xs">
        <p className="text-body-md font-medium text-[var(--opaline-on-surface)]">Summary generated locally</p>
        <p className="mt-1 text-caption text-[var(--opaline-on-surface-variant)]">
          The summary was generated, but it couldn’t be synced to the server yet.
        </p>
        <button
          type="button"
          onClick={onRetrySave}
          className="mt-3 inline-flex items-center gap-1.5 rounded-lg bg-[var(--opaline-primary)] px-3 py-1.5 text-xs font-medium text-[var(--opaline-on-primary)] transition-colors hover:bg-[var(--opaline-primary-hover)]"
        >
          <RefreshCw className="h-3 w-3" aria-hidden /> Retry save
        </button>
      </div>
    );
  }

  if (state === 'failed') {
    return (
      <div className="rounded-xl border border-[var(--opaline-outline-variant)] bg-[var(--opaline-surface-container-lowest)] p-5 shadow-xs">
        <p className="text-body-md font-medium text-[var(--opaline-on-surface)]">Local summarization failed</p>
        <p className="mt-1 text-caption text-[var(--opaline-on-surface-variant)]">
          {error || 'The local model could not summarize this meeting. Your transcript is unchanged.'}
        </p>
        <div className="mt-3 flex gap-2">
          {onRegenerate && (
            <button
              type="button"
              onClick={onRegenerate}
              className="inline-flex items-center gap-1.5 rounded-lg bg-[var(--opaline-primary)] px-3 py-1.5 text-xs font-medium text-[var(--opaline-on-primary)] transition-colors hover:bg-[var(--opaline-primary-hover)]"
            >
              <RefreshCw className="h-3 w-3" aria-hidden /> Retry
            </button>
          )}
          <button
            type="button"
            onClick={() => router.push('/settings?tab=Transcriptionmodels')}
            className="rounded-lg px-3 py-1.5 text-xs font-medium text-[var(--opaline-on-surface-variant)] transition-colors hover:bg-[var(--opaline-surface-container-low)]"
          >
            Choose another model
          </button>
        </div>
      </div>
    );
  }

  // Structured local summary: { summary, keyPoints, decisions, ..., modelName, generatedLocally, generatedAt }
  if (summary && (summary.summary || Array.isArray(summary.keyPoints))) {
    return (
      <div className="rounded-xl border border-[var(--opaline-outline-variant)] bg-[var(--opaline-surface-container-lowest)] p-5 shadow-xs">
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-1.5 text-overline text-[var(--opaline-on-surface-variant)]">
            <Sparkles className="h-3.5 w-3.5 text-[var(--opaline-primary)]" aria-hidden />
            Summary
          </div>
          {summary.generatedLocally && (
            <span className="text-caption text-[var(--opaline-outline)]">
              Generated locally{summary.modelName ? ` · ${summary.modelName}` : ''}
            </span>
          )}
        </div>

        {summary.summary && (
          <p className="mt-3 text-body-sm leading-relaxed text-[var(--opaline-on-surface)]">{summary.summary}</p>
        )}

        <div className="mt-2">
          <Section title="Key points" items={summary.keyPoints ?? []} />
          <Section title="Decisions" items={summary.decisions ?? []} />
          <Section title="Action items" items={summary.actionItems ?? []} />
          <Section title="Customer requirements" items={summary.customerRequirements ?? []} />
          <Section title="Objections & concerns" items={summary.objections ?? []} />
          <Section title="Follow-ups" items={summary.followUps ?? []} />
        </div>

        {onRegenerate && (
          <div className="mt-4 flex items-center gap-2 border-t border-[var(--opaline-outline-variant)] pt-3">
            <button
              type="button"
              onClick={onRegenerate}
              className="inline-flex items-center gap-1.5 rounded-lg border border-[var(--opaline-outline-variant)] px-3 py-1.5 text-xs font-medium text-[var(--opaline-on-surface)] transition-colors hover:bg-[var(--opaline-surface-container-low)]"
            >
              <RefreshCw className="h-3 w-3" aria-hidden /> Regenerate
            </button>
          </div>
        )}
      </div>
    );
  }

  // No summary yet.
  return (
    <div className="rounded-xl border border-[var(--opaline-outline-variant)] bg-[var(--opaline-surface-container-lowest)] p-6 text-center shadow-xs">
      <p className="text-body-md font-medium text-[var(--opaline-on-surface)]">No summary yet</p>
      <p className="mx-auto mt-1 max-w-sm text-caption leading-relaxed text-[var(--opaline-on-surface-variant)]">
        Summaries are generated locally on your machine with the model you choose — no transcript is sent to a server.
      </p>
      <button
        type="button"
        onClick={() => router.push('/settings?tab=Transcriptionmodels')}
        className="mt-4 inline-flex items-center gap-1.5 rounded-lg bg-[var(--opaline-primary)] px-3 py-1.5 text-xs font-medium text-[var(--opaline-on-primary)] transition-colors hover:bg-[var(--opaline-primary-hover)]"
      >
        <Download className="h-3 w-3" aria-hidden /> Set up a local summary model
      </button>
    </div>
  );
};
